#!/bin/sh
# RAR-Archiver
# Copyright (c) 2021, chris1111. All Right Reserved
# (rar) Copyright (c) Alexander Roshal
# (unar) Copyright (c) Aaron Shang
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# Vars
TempDir="/Private/tmp/Extract"
appname="RAR-Archiver"
version="1.0"
export ICNS=$(dirname "${0}")
iconfile="$ICNS/AppIcon.icns"
rm -rf "${TempDir}"
echo " "
echo " "
echo $appname $version
date=`date -j +%Y%m%d-%H%M%S`
Sleep 1

# Set Droping directory and file
for files in "$@" ;do

mkdir -p "${TempDir}"
Sleep 1

cp -R "$@" "${TempDir}"

echo "Prepare Installation for:"
for file in "${TempDir}"/*;
do
echo "${file##*/}"
done


Sleep 2
# Select Choice
response=$(osascript -e 'tell app "System Events" to display dialog "RAR-Archive can compress any type of files. Except for an Application, and a Folder; if you have an .App or folder, make sur you have compress it into a Zip file before dragging it into the window.

RAR-Archive can extract .rar, .7Z , .ZIP, .TAR, .GZIP, .BZIP2, .XZ, payload, Scripts, .pkg." buttons {"Cancel","Extract","Archive RAR"} default button 3 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)

  #  Exit if Canceled
  if [ "$action" == "Cancel" ] ; then
    osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'     
     exit 0
  fi
 

  #  Extract
  if [ "$action" == "Extract" ] ; then
for file in "${TempDir}"/*;
do
Sleep 1
echo "Creating Backup RAR Directory on Desktop"
mkdir -p "${3}"/$HOME/Desktop/RAR/$date
./unar -r "$@" -o ~/Desktop/RAR/$date
done
osascript -e 'tell app "System Events" to display dialog "File extracted on Desktop/RAR" buttons {"Done"} default button 1 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  '
rm -rf "${TempDir}"
Open "${3}"/$HOME/Desktop/RAR/$date
fi


### Archive RAR
if [ "$action" == "Archive RAR" ] ; then
for file in "${TempDir}"/*;
do
Sleep 1
echo "Creating Backup RAR Directory on Desktop"
mkdir -p "${3}"/$HOME/Desktop/RAR/$date
cp -R ./Rar "${TempDir}"
Sleep 1
cp -R "$@" "${TempDir}"
Sleep 2
cd /Private/tmp/Extract
./Rar/rar a /Private/tmp/Extract/Archive$date
mv /Private/tmp/Extract/*.rar ~/Desktop/RAR/$date


done
osascript -e 'tell app "System Events" to display dialog "File compress on Desktop/RAR" buttons {"Done"} default button 1 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  '
rm -rf "${TempDir}"
Open "${3}"/$HOME/Desktop/RAR/$date
fi

done
